name: ClearHotbarCommands
version: 1.0
author: Mxtery
main: com.websiteofgames.clearhotbar.ClearHotbar
api-version: 1.17
commands:
  clearhotbar:
    description: Clears player's hotbar
    usage: /<command>
    aliases: chb
  clearhands:
    description: Clears both of player's hands
    usage: /<command>
    aliases: chs
  clearhand:
    description: Clears player's main hand
    usage: /<command>
    aliases: ch
  clearoffhand:
    description: Clears player's off hand
    usage: /<command>
    aliases: coh
  cl:
    description: Clears player's inventory after giving them a prompt
    usage: /<command>
  clearhotbarslot:
    description: Clears specific player hotbar slot
    usage: /<command>
    aliases: chbs
  cleararmor:
    description: Clears player armour
    usage: /<command>
    aliases: [cleararmour, ca]


