name: ClearHotbarCommands
version: 1.0
author: Mxtery
main: com.websiteofgames.clearhotbar.ClearHotbar
api-version: 1.18
commands:
  clearhotbar:
    description: Clears player's hotbar
    usage: /<command> <name of player you want to target>
    aliases: chb
  clearhands:
    description: Clears both of player's hands
    usage: /<command> <name of player you want to target>
    aliases: chs
  clearhand:
    description: Clears player's main hand
    usage: /<command> <name of player you want to target>
    aliases: ch
  clearoffhand:
    description: Clears player's off hand
    usage: /<command> <name of player you want to target>
    aliases: coh
  cl:
    description: Clears player's inventory after giving them a prompt
    usage: /<command> <player who you want to clear>
  clearhotbarslot:
    description: Clears specific player hotbar slot
    usage: /<command> <hotbarslot>
    aliases: chbs
  cleararmor:
    description: Clears player armour
    usage: /<command> <name of player you want to target>
    aliases: [cleararmour, ca]
  copyinv:
    description: Copies a player's inventory
    usage: /<command> <name of player you want to target>



