name: InvManageCommands
version: 1.5
author: Mxtery
main: me.mxtery.invmanagecommands.InvManage
api-version: 1.18
commands:
  clearhotbar:
    description: Clears target's hotbar
    usage: /<command> <name of player you want to target>
    aliases: chb
  clearhands:
    description: Clears both of the target's hands
    usage: /<command> <name of player you want to target>
    aliases: chs
  clearhand:
    description: Clears target's main hand
    usage: /<command> <name of player you want to target>
    aliases: ch
  clearoffhand:
    description: Clears target's off hand
    usage: /<command> <name of player you want to target>
    aliases: coh
  cl:
    description: Clears target's inventory after giving them a prompt
    usage: /<command> <player who you want to clear>
  clearhotbarslot:
    description: Clears specific hotbar slot
    usage: /<command> <hotbarslot>
    aliases: chbs
  cleararmor:
    description: Clears target's armour
    usage: /<command> <name of player you want to target>
    aliases: [cleararmour, ca]
  copyinv:
    description: Copies a player's inventory
    usage: /<command> <name of player you want to target>
    permission: invmanagecommands.copyinv
    permission-message: §cYou don't have the required permission (invmanagecommands.copyinv)
  invmanage:
    description: Opens target's invetory
    usage: /<command> <target player>
    permission: invmanagecommands.invmanage
    permission-message: §cYou don't have the required permission (invmanagecommands.invmanage)



